language: objective-c
before_install:
    - gem install cocoapods --no-rdoc --no-ri --no-document --quiet
    - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
    - pod install
    - sudo easy_install cpp-coveralls
script:
    - make clean test-with-coverage
after_success:
    - make send-coverage